source "http://rubygems.org"

gem 'rspec'
gem 'page-object'
gem 'require_all'
gem 'net-ssh', :require => 'net/ssh'
gem 'expect4r'
gem 'ci_reporter'
gem 'net-scp'
gem 'rbvmomi'
gem 'snmp'
gem 'rest-client'
gem 'matches'
gem 'watir-webdriver'
gem 'data_magic'
gem 'ruby-tcl'
gem 'fastercsv'
gem 'net-sftp'
gem 'win32-process'
gem 'selenium-webdriver'